"""Tests for the SOWSmith renderer."""
from __future__ import annotations

from sowsmith import SOW_VERSION, build_sow_markdown


def _minimal_envelope() -> dict:
    return {
        "schema_version": "orbitbrief.input.v2",
        "project_id": "test_project",
        "compile_id": "cmp_test123",
        "generated_at": "2026-05-22T00:00:00Z",
        "summary": {"artifact_count": 3, "atom_count": 42, "page_count": 5},
        "atoms": [],
        "edges": [],
        "packets": [],
        "entities": [],
        "indexes": {},
    }


def test_renders_minimal_envelope_to_markdown():
    md = build_sow_markdown(_minimal_envelope())
    assert md.startswith("# Statement of Work — Test Project")
    assert "**Project ID:** `test_project`" in md
    assert "**Compile ID:** `cmp_test123`" in md
    assert "Generated by SOWSmith" in md
    assert SOW_VERSION in md


def test_renders_all_17_sections():
    md = build_sow_markdown(_minimal_envelope())
    expected_headings = [
        "## 1. Executive Summary",
        "## 3. Stakeholders",
        "## 4. Sites & Locations",
        "## 5. Scope of Work",
        "## 6. Change Order History",
        "## 7. Out of Scope",
        "## 8. Schedule & Milestones",
        "## 9. Commercial Terms",
        "## 10. SLA & Support Terms",
        "## 11. Site Access, Safety & Constraints",
        "## 12. Acceptance Criteria",
        "## 13. Risk Register",
        "## 14. Open Questions Before Kickoff",
        "## 15. Readiness Audit",
        "## 16. Evidence Trail — Contested Claims",
    ]
    for h in expected_headings:
        assert h in md, f"missing section: {h}"


def test_missing_fields_surface_explicitly():
    md = build_sow_markdown(_minimal_envelope())
    # Minimal envelope has no stakeholders / sites / scope / etc.,
    # so the SOW should surface [NEEDS DATA] placeholders rather
    # than rendering empty tables.
    assert "[NEEDS DATA" in md


def test_renders_project_vitals_when_present():
    env = _minimal_envelope()
    env["project_vitals"] = {
        "score_100": 88.5,
        "band": "yellow",
        "top_drivers": ["sow_readiness"],
        "top_detractors": ["contradiction_health"],
        "components": [
            {"name": "sow_readiness", "weight": 0.30, "raw_score": 0.88, "contribution": 0.264},
        ],
    }
    md = build_sow_markdown(env)
    assert "## 2. Project Vitals" in md
    assert "88.5 / 100" in md
    assert "YELLOW" in md
    assert "**Readiness:** **88.5 / 100** &nbsp;·&nbsp; **MINOR GAPS**" in md


def test_renders_scope_truth_with_contested_audit():
    env = _minimal_envelope()
    env["scope_truth"] = {
        "device_count": 1,
        "site_count": 1,
        "contested_count": 1,
        "devices": [
            {
                "device": "device:ip_camera",
                "site": "site:west_wing",
                "canonical_quantity": 36,
                "governing_authority": "contractual_scope",
                "is_contested": True,
                "all_reported_values": [36, 48],
            },
        ],
        "contested": [
            {
                "device": "device:ip_camera",
                "site": "site:west_wing",
                "canonical_quantity": 36,
                "competing_values": [48],
                "audit": [
                    {"quantity": 36, "claims": [{"atom_id": "atm_a", "authority_class": "contractual_scope", "text": "36 cameras"}]},
                    {"quantity": 48, "claims": [{"atom_id": "atm_b", "authority_class": "contractual_scope", "text": "48 cameras"}]},
                ],
            },
        ],
    }
    md = build_sow_markdown(env)
    assert "## 5. Scope of Work" in md
    assert "Ip Camera" in md
    assert "**36**" in md  # governing value
    assert "## 16. Evidence Trail" in md
    assert "Competing:** 48" in md or "Competing: 48" in md
    assert "atm_a" in md
    assert "atm_b" in md


def test_renders_change_order_with_delta():
    env = _minimal_envelope()
    env["change_order_timeline"] = {
        "entry_count": 1,
        "with_structured_delta": 1,
        "with_approval_signal": 0,
        "entries": [
            {
                "atom_id": "atm_c1",
                "kind": "customer_instruction",
                "text": "Please reduce camera count from 48 to 36",
                "change_delta": {"from": 48, "to": 36, "delta": -12},
                "approval_signal": False,
                "sort_key": ["a1", 0, 0, "atm_c1"],
            },
        ],
    }
    md = build_sow_markdown(env)
    assert "## 6. Change Order History" in md
    assert "48 → 36 (-12)" in md


def test_renders_stakeholders_with_workload():
    env = _minimal_envelope()
    env["pm_dashboard"] = {
        "stakeholders": [
            {"slug": "sarah_chen", "name": "Sarah Chen", "role": "Project Sponsor", "email": "schen@acme.com", "phone": ""},
        ],
        "money_summary": {"total": 0, "atoms": []},
    }
    env["stakeholder_load"] = {
        "stakeholder_count": 1,
        "stakeholders": [
            {
                "slug": "sarah_chen",
                "risk_count": 2,
                "critical_risk_count": 1,
                "high_risk_count": 1,
                "action_item_count": 0,
                "risk_severity_load": 8,
            },
        ],
        "bottlenecks": [],
    }
    md = build_sow_markdown(env)
    assert "## 3. Stakeholders" in md
    assert "Sarah Chen" in md
    assert "Project Sponsor" in md
    assert "schen@acme.com" in md
    assert "**Workload allocation:**" in md
    assert "sarah_chen" in md
    assert "| 2 | 1 | 1" in md  # risks=2, critical=1, high=1


def test_renders_risk_register_sorted_by_severity():
    env = _minimal_envelope()
    env["pm_dashboard"] = {
        "stakeholders": [],
        "risks_by_owner": {
            "owner_a": [
                {"risk_id": "R-001", "severity": "Low", "summary": "Low risk", "mitigation": "Watch"},
                {"risk_id": "R-002", "severity": "Critical", "summary": "Critical risk", "mitigation": "Mitigate now"},
                {"risk_id": "R-003", "severity": "High", "summary": "High risk", "mitigation": "Pre-stage"},
            ],
        },
        "risks_unowned": [],
        "money_summary": {"total": 0, "atoms": []},
    }
    md = build_sow_markdown(env)
    assert "## 13. Risk Register" in md
    # Critical should appear before High, High before Low
    crit_pos = md.find("R-002")
    high_pos = md.find("R-003")
    low_pos = md.find("R-001")
    assert crit_pos < high_pos < low_pos, f"risks not sorted by severity (positions: critical={crit_pos}, high={high_pos}, low={low_pos})"


def test_deterministic_output():
    env = _minimal_envelope()
    md1 = build_sow_markdown(env)
    md2 = build_sow_markdown(env)
    assert md1 == md2  # byte-identical on same input
